AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # EBS設定
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: standard
            VolumeSize: 10
      ImageId: ami-940cdceb
      InstanceInitiatedShutdownBehavior: 'stop'
      InstanceType: 't2.micro'
      Monitoring: false
      KeyName : '2018-08-19'
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.1.10
          DeviceIndex: 0
          GroupSet:
          - sg-08cef5c614ff1013a
          SubnetId:
            Fn::ImportValue: cfn-practice-network-MyPublicSubnet # ここ動的に変えたい

      # テナンシー
      Tenancy: 'default'
