AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # EBS設定
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: standard
            VolumeSize: 10
      ImageId: ami-940cdceb
      InstanceInitiatedShutdownBehavior: 'stop'
      InstanceType: 't2.micro'
      Monitoring: false
      KeyName : '2018-08-19'
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          PrivateIpAddress: 10.0.1.11
          DeviceIndex: 0
          GroupSet:
          - sg-0869cfdf7a1b20449
          SubnetId:
            Fn::ImportValue: cfn-practice-network-MyPublicSubnet # ここ動的に変えたい

      # テナンシー
      Tenancy: 'default'
  InstanceDNSRecord :
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: yux3.net.
        Comment: "A record for the instance."
        Name : test.yux3.net.
        Type : CNAME
        TTL : 300
        ResourceRecords :
          - !GetAtt MyEC2Instance.PublicDnsName
