AWSTemplateFormatVersion: "2010-09-09"
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: base
      GroupDescription: Allow ssh
      VpcId:
          Fn::ImportValue: cfn-practice-network-MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
